general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Redupkan layar setelah 4 menit
listener {
    timeout = 240
    on-timeout = brightnessctl -s set 20%
    on-resume = brightnessctl -r
}

# Lock setelah 5 menit
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Monitor off setelah 8 menit
listener {
    timeout = 480
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend setelah 30 menit
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
